language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8
  - openjdk8

before_cache:
  - rm -rfv $HOME/.m2/repository/io/github/mweirauch/micrometer-jvm-extras

cache:
  directories:
  - $HOME/.m2

install: /bin/true

script: mvn clean install
